= My Curriculum Vitae/Resume

image:https://github.com/dduportal/cv/actions/workflows/main.yaml/badge.svg["Build Status", link="https://github.com/dduportal/cv/actions/workflows/main.yaml/badge.svg"]

This repository hosts my curriculum vitae.

== Why

As a software engineer, I wanted my CV to follow my professional practices :

* Source text based to easily use SCMs, merging, diffing, history
* Publicly available, shareable, editable
* HTML W3C compliant but also PDF format to ease reading

== What

* CV content is written in link:https://asciidoctor.org/[Asciidoctor]

* Continuous Deployment uses link:https://github.com/features/actions[GitHub Actions] which generates the HTML and PDF outputs, validate them and deploy them.

* Production (where the CV is deployed and served) uses link:https://pages.github.com/[Github Pages].

== How

=== Requirements

* Make
* Docker and Docker-Compose

=== Build

Run the following commands to:

* Build all the outputs:
+
[source,bash]
----
make build
----

* Build the HTML output:
+
[source,bash]
----
make html
----


* Build the PDF output:
+
[source,bash]
----
make pdf
----

// === Local

// Open you browser to the page, using your Docker Engine IP :

// ```text
// http://<YOUR DOCKER ENGINE IP>:4000
// ```

== Licensing

This repository is provided on the link:http://www.gnu.org/licenses/license-list.html#ISC[ISC license].

You will find the License link:./LICENSE.adoc[here].

It means you can use the content only if you make it appear with the same license.
